POST http://localhost:8000/bands
Content-Type: application/json

{
  "name": "Boards of Canada",
  "genre": "ELECTRONIC",
  "albums": [
    {
      "title": "abc",
      "release_date": "2013-01-01"
    },
    {
      "title": "cda",
      "release_date": "1998-03-20"
    }
  ]
}

###

GET http://localhost:8000/bands?genre=electronic